### ISSUE TITLE
VocabActivity

### ISSUE THREAD

**Issue by lethargilistic** [truffLabs/cs142ReviewApp#10]

**Comment by truffLabs** [comment]
Need to add content and scrolling but otherwise I think it is done.

**Comment by truffLabs** [comment]
Was planning to get content from:
https://apcswshs.wikispaces.com/Glossary+of+Terms

**Comment by lethargilistic** [comment]
Hm. It would be trivial to separate these into a map of words to definitions using a regular expression. An idea on how to expand this Activity from just a text page might be to have a ListView of buttons with the words on them. When you click a button, you go to the definition. You could press back or use the MenuBar to navigate back to other content.

**Comment by lethargilistic** [comment]
I'm including a Vocab.txt file in the repo for now.

**Comment by truffLabs** [comment]
I set up a DB that reads in the words and definitions from the text file. Need to work on getting a list view where you select the word to see the definition.

**Comment by truffLabs** [comment]
Merged in
-reads file
-interactive
