### ISSUE TITLE
AllResultsActivity

### ISSUE THREAD

**Issue by lethargilistic** [truffLabs/cs142ReviewApp#11]

**Comment by truffLabs** [comment]
I have made the backend DB. In OneResult is adds the result. In ViewResults it should query the DB.

Here are the two URLs
//implemented
http://cssgate.insttech.washington.edu/~htroy/addResult.php?email=toddme&result=5000&date=2016-7-31
//working on now
http://cssgate.insttech.washington.edu/~htroy/getUserResults.php?email=toddme

**Comment by truffLabs** [comment]
Implemented webDB end of ResultsActivity.  Currently just populates a text view.  Still need to do #1 and format better as wanted.  I'm going to pause my work on this issue for now.

**Comment by truffLabs** [comment]
Reimplemented
