### ISSUE TITLE
MockTestActivity

### ISSUE THREAD

**Issue by lethargilistic** [truffLabs/cs142ReviewApp#13]

**Comment by lethargilistic** [comment]
It seems the last thing to do here is implementing storing the results of each test.

Our UML says this should be done in the ResultsModel class, which is a result of my talk with Menaka. She said we should keep the updates and retrieval from the results database in one class.

**Comment by truffLabs** [comment]
I think she is referring to one local DB, but I envision this as a webDB thing.  After TurnIn1 I will help with the PHP and web DB

**Comment by truffLabs** [comment]
I'm still working on MockTestActivity, but the call to launch OneResultActivity is crashing the app.  Not sure if it is do to MockTestActivity work or other reason.

-Getting Questions...
   -I have overhauled DBHelper
      -no need for local DB
      -calls WebDB to get 40 random questions via PHP
           http://cssgate.insttech.washington.edu/~htroy/checkUser.php
      -randomness is done on server side
   -need to implement observer/observable 
      -so MockTestModel waits till DBHelper is done loading Q's

**Comment by truffLabs** [comment]
Besides formatting issues covered by issue #30 I think we have this down.
