### ISSUE TITLE
Check marks in OneResultActivity

### ISSUE THREAD

**Issue by lethargilistic** [truffLabs/cs142ReviewApp#23]
We could add a graphic check mark or a box in the list, like on our original diagrams. Totally an optional enhancement.

**Comment by truffLabs** [comment]
I'm not worried about the check mark but it would be nice to have the results be more informative by allowing the user to see the Q and answer.  I think this is low priority though.

**Comment by truffLabs** [comment]
Going to work on this over next few days.

**Comment by truffLabs** [comment]
Made interactive!
