### ISSUE TITLE
ActionBarActivity

### ISSUE THREAD

**Issue by truffLabs** [truffLabs/cs142ReviewApp#28]
I reverted the activities to ActionBarActivity from Activity so the Action Bar is shown in branch 5.  ActionBarActivity is deprecated but we need to figure out a better option to switch it to to the menu still shows.

**Comment by lethargilistic** [comment]
Ah, I see. I didn't realize that was to show the menu bar. My bad.

**Comment by lethargilistic** [comment]
We need to add the options to AllResultsActivity, OneResultActivity. Perhaps MockTestActivity.

**Comment by lethargilistic** [comment]
Also, you mentioned adding AllResultsActivity to the bar.

**Comment by truffLabs** [comment]
Done
