### ISSUE TITLE
How will we store percentages in the SQL database?

### ISSUE THREAD

**Issue by lethargilistic** [truffLabs/cs142ReviewApp#3]
Our UML diagram says to do this with double. However, if we use doubles for the calculations then that opens us up to rounding errors, so we'd have to round to some number of decimal places anyway. 

At that point, we might decide to use integers for the math and storage (10000 -> 100.00%).

Another option for storage of this data is to store a string; after all, we won't be calculating an overall percentage of all the test attempts, so each test's final result will be static.

**Comment by truffLabs** [comment]
The value should be 0-40 so your 10000 -> 100.00% idea seems logical.  Other option is display: "## / 40"

**Comment by truffLabs** [comment]
0 - 10000. Closed.
