### ISSUE TITLE
ResourcesActivity

### ISSUE THREAD

**Issue by truffLabs** [truffLabs/cs142ReviewApp#37]
Here is a link to the GoogleDrive folder with the documents.
https://drive.google.com/folderview?id=0B46FydfURJ93SHZIQ21EQ3JUenc&usp=sharing

**Comment by lethargilistic** [comment]
**Some ideas**
* PDF shown directly in the app (is that possible?)
* Student checks which resources they want from the list and can push a button to email themselves a set of links to the resources.
* Separate the chapters from the slides.

**Comment by lethargilistic** [comment]
The resource links are as follows. Click the edit button to get the plaintext: 
### Chapters
* AP-CS-Java-Syntax-Summary-5.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ODRIS2x4NkZ6RGs/preview
* Ch0 StyleGuide.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93RHltUTVET2lXbUk/preview
* Ch1 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93aHlhRGhWUEZ2UkE/preview
* Ch2 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93XzRwMTVWeTJvRmc/preview
* Ch3 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93WlNLWkVQQXdib28/preview
* Ch4 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ZnZTNFYyOG1sWHM/preview
* Ch5 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93eUo0ZElEZ00xdUk/preview
* Ch6 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93b01iQk1LRDB1NEU/preview
* Ch7 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93dUdhc0hVNFRKRFk/preview
* Ch7.2 CheatSheet 2D Arrays.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93WFpaR1phY2Frejg/preview
* Ch8 CheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93dWppNkdaRExoTTA/preview
* Ch8.3 CheatSheet ArrayList.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ajFFSjJubU8wdUU/preview
* Ch9.1 CheatSheet Interfaces-Comparable.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ZUJ1RnN4Wm90TG8/preview
* FinalCheatSheet.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93U3ZuUXd4SkdMNW8/preview

###Slides
* 01-ch01-1-println.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93bE5EOU9xTERWY1k/preview
* 02-ch01-2-methods.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93VGJUR0tVOENTMEE/preview
* 03-ch02-1-expressions.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93OXZiUjdIenJVMFk/preview
* 04-ch02-2-forloops.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93YWVUb0R5dkRpQUk/preview
* 05-ch02-3-constants.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93dFhMdS1YVThTZVk/preview
* 06-ch03-1-parameters.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93bF9CWFFNZk9iOWs/preview
* 07-ch03g-graphics.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ZUM2S01pdVk5Y00/preview
* 08-ch03-2-return.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93YmFDUWFRamdwLXc/preview
* 09-ch03-3-scanner.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93TXNuakNtMDI1RGs/preview
* 10-ch04-1-ifelse.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93aFdlZ0ZKVmtER1E/preview
* 11-ch04-2-strings.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93MkxKU1NfdGxIbFk/preview
* 12-ch05-1-while.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93Yk1UVE8xNWlCSFU/preview
* 13-ch05-2-random.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93TnB2bk1aM0dmbFk/preview
* 14-ch05-3-boolean.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93R1doZm5TdElPQms/preview
* 15-ch05-4-assertions.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ajdSWWluQnZOY0E/preview
* 16-ch06-1-files.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93ODJPRVRjUjRIM00/preview
* 18-ch06-3-searching.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93Y2dxR0FUcXhkeHc/preview
* 19-Ch7Arrays.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93bFgwWk5tWHA5MGs/preview
* 19-Ch8Objects.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93VWdpNVBvRTQwVUE/preview
* 20-8.3ArrayListSlides.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93TjZCSzQyME1ib3M/preview
* 22-Compares-compareTo.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93XzM1SUV0VWJ2OUU/preview
* 23-Inheritance.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93X3J2WjFRRl9UUWs/preview
* 24-2D Arrays.pdf https://drive.google.com/a/uw.edu/file/d/0B46FydfURJ93YVRzaTI0RDItWUU/preview

**Comment by truffLabs** [comment]
I like the:
Student checks which resources they want from the list and can push a button to email themselves a set of links to the resources.
idea.  But I will defer to you.

Let me know if you run into trouble.

**Comment by truffLabs** [comment]
Would be nice if links were in a file and read into app so could be changed in future.  Like the vocab set up.

**Comment by lethargilistic** [comment]
I'm doing the email version, and have a basic version working for just the Chapters. I'm going to try making a swiping fragment to include the Slides.

As for the file, I've started trying to incorporate the file reading. However, since the flag file is stored within the app, it's basically the same as creating the maps from topic to link (and word to definition) with a function within the activity. To get any changes to the flag files, a student would have to update the app.

If you want to be able to change these flag files and have it update for everyone using the app, perhaps we should store them on the server? If we were to do that, we could elect to just have a SQL database on the server, but I think, for the assignment, we need to use the on-phone SQLite at some point.

**Comment by truffLabs** [comment]
Sounds good.

The VocabActivity uses SQLite. Don't worry about the file reading thing.  I think I might try to implement it some day, but not necessarily for the project.  As you guessed I'm hoping to keep tinkering with the app after this quarter. 

My thought was by having the main files there, like vocab, chapterTitles, resource links, that these files could be swapped out and the app could be used for other subjects too.  I'm not thinking being able to hot-swap the data, like for the questions, but update as needed for future builds.  I plan to use the chapterTitles file to build a Map<String,String> to use, some thing that currently is hard coded.  Does this make sense?
