### ISSUE TITLE
Presentation date

### ISSUE THREAD

**Issue by truffLabs** [truffLabs/cs142ReviewApp#42]
Its looking like I will be out of town as of 8/15.  What would you think of offering to present are app this Thr (8/13)?  I think even with resources #37 not 100% we could present and then complete for final submission.

**Comment by lethargilistic** [comment]
I'd be fine with that. ResourcesActivity is definitely a minimum viable product at the moment, with all the chapters. We don't even have to mention the slides, necessarily.

**Comment by truffLabs** [comment]
Prof just emailed back and we are on to present Thr. We can talk tomorrow about who's device and such.
